### PR TITLE
Custom error messages

### PR DESCRIPTION
**Pull request by killian90**
@VojtechBartos not sure if you want to CR this, or maybe just take a look at tests or what - can skype and explain stuff to you if you like - would be awesome to release to QA this evening if possible, so let me know :+1:

### CODE REVIEW

**Comment by killian90** [comment]
@VojtechBartos bump :)

**Comment by killian90** [comment]
@VojtechBartos bump / ping / :rabbit:

**Comment by killian90** [comment]
@VojtechBartos :eyes: :smile:

**Comment by VojtechBartos** [comment]
@killian90 it's looking good, but have you been thinking about creating proper PR to original repository as well ?

**Comment by killian90** [comment]
@VojtechBartos Yeah it's definitely worth looking at, but it's tough for a couple of reasons:
- It includes some stuff from a different fork as well, so would need to co-ordinate with them.
- The original repo has a submodule of the JSON-Schema-Test-Suite, but I've included all the files in the actual project (to add in the messages we want to display), and it might not be the way the original repo want's to go.

Definitely worth talking to him about it, and I probably will over the next couple of days / weeks. Just interested in getting our stuff done first ;)

**Comment by VojtechBartos** [comment]
@killian90 yeah, i mean it would make definitely sense to create first issue and just ask if they would be interested to have the feature ;)

**Pull request merged**
